// packages/shared/src/index.ts
export * from './types/index';
export {
  dnsConfigurationSchema,
  parseStringList,
  stringListRefinement,
  isValidIpAddress,
  isNonEmptyString,
  isNumeric,
  RECORD_TYPES,
  dnsRecordUISchema,
  dnsConfigSchema,
  uiZoneSchema,
  transformUiRecordToApiRecord,
  parseStringToArray,
  transformFormToApiData,
  // HTTP validators and transformers
  isValidPort,
  isValidPath,
  isValidServerName,
  isValidEmail,
  virtualHostSchema,
  httpConfigSchema,
  transformUiVirtualHostToApi,
  transformApiVirtualHostToUi,
  parsePortString,
  transformHttpFormToApi,
  transformHttpApiToForm,
  // DHCP validators and transformers
  dhcpIsValidIpAddress,
  isValidMacAddress,
  isValidNetmask,
  isValidHostname,
  isValidDomainName,
  isValidLeaseTime,
  isIpInNetwork,
  isValidIpRange,
  dhcpOptionSchema,
  hostReservationSchema,
  subnetSchema,
  dhcpConfigSchema,
  transformDhcpFormToApi,
  transformDhcpApiToForm,
  dhcpParseStringToArray,
  arrayToCommaString,
  validateDhcpFormData,
  generateDefaultDhcpConfig,
  calculateBroadcastAddress,
  calculateNetworkAddress,
  suggestIpRange,
  createTicketSchema,
  updateTicketSchema,
  createTicketFormSchema
} from './validators';